name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Send Telegram
        uses: say8425/send-telegram-action@v1
        with: 
          telegram_key: ${{ secrets.TELEGRAM_KEY }}
          chat_id: '-34404145'
          text: Hello World!

