name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Telegram
        uses: say8425/sent-teleram-action@v1
        with: 
          key: {{ secrets.TELEGRAM_KEY }}
          chat_id: '-344041454'
          text: Hello World!
